### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by loon123456** [rapid7/hackazon#9]
Error 42S02: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hackazon.tbl_product_options_values' doesn't exist

**Comment by birising** [comment]
Yes, I am getting same error

**Comment by adilhf** [comment]
Same error here! It looks like not much person got this error..

**Comment by adilhf** [comment]
Well, to name the problem, its simply an issue of "connecting php to mysql database" but i still struggling with it..

**Comment by adilhf** [comment]
I find some way to solve the issue, its here: https://community.rapid7.com/thread/9330

**Comment by gmaran23** [comment]
I have this error, I have posted a fix that worked for me here at 

https://renouncedthoughts.wordpress.com/2017/02/21/getting-hackazon-up-and-running-on-wamp-on-nov-2016/ 

I had to add the below line at the top of the C:\home\hackazon\database\db.sql file.

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

**Comment by DenisPodgurskiy** [comment]
There is a fix commited for db.sql script that should fix this issue.
If you still have this one - please let me know mysql version.

**Comment by OptmizerLLC** [comment]
Getting this same error and google led me to this thread. Brand new Debian 8 VM with MySQL 5.5.58. Cloned hackazon from the repo today.

If there is a better starting platform for fewer issues I'd be happy to switch.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
On Ubuntu 14 (because php5) and mysql 5.5.58 I have the same error (`1146 Table 'hackazon.tbl_product_options_values' doesn't exist`), but when I try: 
```
# mysql -p hackazon < db.sql 
Enter password: 
ERROR 1293 (HY000) at line 41: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```
[The issue is resolved in mysql 5.6](https://stackoverflow.com/questions/4489548/why-there-can-be-only-one-timestamp-column-with-current-timestamp-in-default-cla)

On Debian 9, with MariaDB 10.1, the script works, but hackazon fails because of php7 (see #14)...

:sunflower:

**Comment by br0kenpencil** [comment]
upgrading to mysql 5.6 fixes it :)

**Comment by OptmizerLLC** [comment]
Good find. I finally got around to updating my Debian 8 build and created a Vagrantfile to script everything.
https://github.com/BoogleCloud/debian8-hackazon

**Comment by ashoknkjp** [comment]
I made chaneg to db.sql and upgraded mysql as seen below but still seeing the issue . Can somebody help .
mysql  Ver 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64) using  EditLine wrapper
I am using https://github.com/cmutzel/all-in-one-hackazon
